[install]
# Use online mode for package installation
prefer = "online"

[test]
# Use Vitest for testing
runner = "vitest"

[build]
# Optimize for production builds
minify = true
target = "browser"

[debug]
# Enable source maps for better debugging
sourcemap = true
