name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps
      - name: Run Playwright tests
        run: bunx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && !env.ACT }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: read
    env:
      DEBIAN_FRONTEND: noninteractive
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        id: bun-cache
        with:
          path: |
            ~/.bun
            node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - name: Install dependencies
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun install
      - name: Type check
        run: bun run check
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun run test

  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test, playwright]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        id: bun-cache
        with:
          path: |
            ~/.bun
            node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            bun-${{ runner.os }}-
      - name: Cache build output
        uses: actions/cache@v4
        id: build-cache
        with:
          path: |
            build
            .svelte-kit
          key: build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            build-${{ runner.os }}-
      - name: Install dependencies
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun install
      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          NODE_ENV: production
        run: bun run build
      - name: Upload Pages artifact
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' && !env.ACT
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/
          retention-days: 30

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read
      pull-requests: read
    steps:
      - name: Deploy to GitHub Pages
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4
